name: test_beacon
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.2.4
  flutter: 
    sdk: flutter
  flutter_beacon: ^0.5.0
  flutter_background: ^1.0.1
  workmanager: ^0.5.0-dev.6
  flutter_local_notifications: ^6.0.0
  flutter_foreground_plugin: ^0.8.0
  flutter_secure_storage: ^4.2.0
  rxdart: ^0.27.1
  android_long_task: ^0.4.5
  uuid: ^3.0.4
  
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  build_runner: ^1.0.0
  objectbox_generator: any

flutter: 
  uses-material-design: true